sudo: required

services:
  - docker

language: python
python:
  - "2.7"

env:
  - DJANGO_SETTINGS_MODULE=conf.settings.testing

before_install:
 - docker-compose pull
 - docker-compose up -d elasticsearch redis
 - docker-compose ps

install:
  - pip install -r requirements/testing.txt
  - nvm install v7.4.0
  - nvm use v7.4.0
  - npm install


script:
  - npm run jsc
  - scripts/tests.sh
  - scripts/pylint.sh
  - scripts/pycodestyle.sh

after_success:
- coveralls
