sudo: required

services:
  - docker

language: python
python:
  - "2.7"

env:
  - DJANGO_SETTINGS_MODULE=conf.settings.testing

before_install:
 - docker-compose pull
 - docker-compose up -d elasticsearch redis
 - docker-compose ps

install:
  - pip install -r requirements/testing.txt

before_script:
  - ./manage.py generate_data --years 300
script:
  - scripts/tests.sh

