version: "3.2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    ports:
      - "9200:9200"
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
      - "xpack.monitoring.enabled=false"
      - "xpack.watcher.enabled"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  postgres:
    image: postgres:9.5.12
    ports:
      - "5432:5432"
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    entrypoint: minio server /data
    volumes:
      - /mnt/data:/data
      - /mnt/config:/root/.minio
    environment:
      - "MINIO_ACCESS_KEY=development"
      - "MINIO_SECRET_KEY=development"
