site_name: API de Series de Tiempo
site_url: http://apis.datos.gob.ar/series/
site_description: Documentación de la API de Series de Tiempo de la República Argentina
site_author: Datos Argentina
repo_url: https://github.com/datosgobar/series-tiempo-ar-api/

nav:
  - Inicio: index.md
  - Usuarios:
    - Comenzar a usar la API de Series de Tiempo: quick-start.md
    - Filtrar y transformar las series: additional-parameters.md
    - Integrar la API en planillas de cálculo: spreadsheet-integration.md
    - Usar en python: python-usage.md
    - Usar en componentes web: js-usage.md
    - Descargar la base completa de series de tiempo: dumps.md
    - Referencia API:
      - /series: 'reference/api-reference.md'
      - /search: 'reference/search-reference.md'
      - /dump: dumps.md
      - /validate: 'reference/validate.md'
      # - OpenAPI: https://datosgobar.github.io/series-tiempo-ar-api/open-api
    - Condiciones de uso: terms.md
  - Aplicaciones: applications.md
  - Publicadores:
    - Publicar series en la API de Series de Tiempo: publishers/quick_start.md
    # - Generar títulos: publishers/titles.md
    - Generar identificadores: publishers/identifiers.md
    - Generar descripciones: publishers/descriptions.md
    # - Elegir unidades de medida: publishers/units.md
    # - Convertir series de XLSX a CSV: publishers/publish-series-xlsx.md
    # - Convertir bases de series en TXT a CSV: publish/publish-series-txt.md
    # - Convertir paneles en series de tiempo: publish/index-series.md
    # - Indexar series de tiempo en la API: publish/index-series.md
  - Desarrolladores:
    - Arquitectura: 'developers/arquitectura.md'
    - Instalación: 'developers/development.md'
    - Administración: 'developers/admin.md'
  - Historial de versiones: 'history.md'

theme: datosgobar_docs

markdown_extensions: [fenced_code, codehilite, admonition]

extra_css:
  - css/extra_rtd.css

google_analytics: ['UA-91435482-1', "https://datosgobar.github.io/series-tiempo-ar-api/"]
