site_name: API de Series de Tiempo
pages:
- Inicio: index.md
- Comienzo rápido: quick_start.md
- Integración con planillas de cálculo: spreadsheet_integration.md
- Referencia API: api_reference.md
- Proyectos de terceros: third_party.md
theme: readthedocs
