---


- name: Install firewall
  apt: name=ufw state=present update_cache=yes

- name: Disable firewall
  ufw:
    state: disabled

- name: Disallow incomming
  ufw:
    direction: incoming
    policy: deny

- name: allow outgoing
  ufw:
    direction: outgoing
    policy: allow

- name: allow application ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ allowed_ufw_ports }}"

- name: Enable firewall
  ufw:
    state: enabled
