---

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and restart web server
  service:
    state: restarted
    name: "{{ item }}"
    enabled: yes
  tags: quickly
  with_items:
    - gunicorn.socket
    - nginx.service

- name: Enable and restart workers
  systemd:
    name: rqworker@{{ item }}.service
    enabled: yes
    state: restarted
  with_sequence: count={{ worker_count }}
