---

- import_playbook: api_cluster.yml
- import_playbook: redis.yml
- import_playbook: elasticsearch.yml

- hosts: apps
  become: yes
  become_method: sudo
  roles:
    - basic_server

- hosts: web
  become: yes
  become_method: sudo
  roles:
    - postgresql
    - { role: maintenance, maintenance_on: yes }


# Use non-root user
# This is a dependency of rqworker group and web group
- hosts: apps
  become: yes
  become_method: sudo
  become_user: "{{ application_user }}"
  roles:
    - django_application

- hosts: rqworker
  become: yes
  become_method: sudo
  roles:
    - rqworker

- hosts: web
  become: yes
  become_method: sudo
  roles:
    - web_server
    - { role: maintenance, maintenance_off: yes }


