---

# Ensure python is installed.
- hosts: api_cluster
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Install python2
      raw: sudo apt-get -y install python

- hosts: api_cluster
  become: yes
  become_method: sudo
  roles:
    - common

- hosts: web
  become: yes
  become_method: sudo
  roles:
    - basic_server
    - { role: maintenance, maintenance_on: yes }
    - postgresql

- hosts: es
  become: yes
  become_method: sudo
  roles:
    - elastic_search

# Use non-root user
- hosts: web
  become: yes
  become_method: sudo
  become_user: "{{ application_user }}"
  roles:
    - django_application

- hosts: web
  become: yes
  become_method: sudo
  roles:
    - web_server
    - { role: maintenance, maintenance_off: yes }


