---

- name: Add backup script
  template: src=bins/psql_backup.sh
            dest={{ psql_backup_bin }}
            owner={{ application_user }}
            group={{ application_group }}
            mode=0770
            backup=yes

- name: Create systemd backup unit file
  template: src=services/psql_backup.service
            dest=/etc/systemd/system/psql_backup.service
            mode=0660
            backup=no
  notify: Enable psql backup timer

- name: Create systemd backup timer file
  template: src=services/psql_backup.timer
            dest=/etc/systemd/system/psql_backup.timer
            mode=0660
            backup=no
  notify: Enable psql backup timer