---

ansible_host: 181.209.63.223
ansible_port: 22215

# This configures Django
es_urls: "http://127.0.0.1:9200/"

# This configures Elasticsearch server
es_bind_host: "127.0.0.1"
es_publish_host: "127.0.0.1"

# This configures Django
default_redis_host: "127.0.0.1"

# This configures Redis server
redis_bind_host: "127.0.0.1"
