---

- name: Install dependencies
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - python3
    - python3-pip
    - python3-venv
    - python3-dev
    - python3-pil

# Somehow required by ansible pip module
- name: Install virtualenv
  pip: 
    name: virtualenv
    executable: pip3
    virtualenv_python: python3.5